#!/usr/bin/env python3
"""
Bundle the analysis outputs into a single JS data file the static
paper-trading app can load with a plain <script> tag (no fetch/CORS/backend
needed). Pulls top-N lists from each analysis, plus recent trade history
for any member who shows up in one of those lists (the "followable" set --
following makes sense for someone the analysis flagged, not a random
back-bencher we have no data on).
"""

import json
from collections import defaultdict

from match_trump_congress import (
    build_trump_index,
    load,
    nearest_trump_match,
    normalize_side,
    parse_date,
    resolve_ticker,
)

TOP_N = 25
RECENT_TRADES_N = 12
WINDOWS = [5, 10, 15, 20]


def compute_matches(trades, filers, trump_idx, window):
    per_filer_matches = defaultdict(int)
    per_filer_trade_count = defaultdict(int)
    for t in trades:
        filer = filers.get(t.get("filer_id"))
        if not filer or filer.get("branch") != "congress":
            continue
        side = normalize_side(t.get("transaction_type"))
        ticker = resolve_ticker(t)
        d = parse_date(t.get("transaction_date"))
        if not side or not ticker or not d:
            continue
        per_filer_trade_count[t["filer_id"]] += 1
        trump_dates = trump_idx.get(ticker, {}).get(side, [])
        if trump_dates and nearest_trump_match(trump_dates, d, window):
            per_filer_matches[t["filer_id"]] += 1

    ranked = []
    for filer_id, count in per_filer_matches.items():
        filer = filers[filer_id]
        total = per_filer_trade_count[filer_id]
        ranked.append(
            {
                "filer_id": filer_id,
                "name": filer.get("full_name"),
                "chamber": filer.get("chamber"),
                "party": filer.get("party"),
                "state": filer.get("state"),
                "match_count": count,
                "total_trades": total,
                "match_rate": round(count / total * 100, 1) if total else 0,
            }
        )
    ranked.sort(key=lambda r: (-r["match_count"], -r["match_rate"]))
    return ranked[:TOP_N]


def main():
    trades, filers = load()
    trump_idx = build_trump_index(trades)

    matches_by_window = {}
    followable = set()
    for w in WINDOWS:
        top = compute_matches(trades, filers, trump_idx, w)
        matches_by_window[str(w)] = top
        followable.update(r["filer_id"] for r in top)

    permutation_by_window = {}
    for w in WINDOWS:
        try:
            with open(f"output/permutation_{w}d.json") as f:
                perm = json.load(f)
        except FileNotFoundError:
            perm = []
        top = [r for r in perm if r["significant_p05"]][:TOP_N]
        permutation_by_window[str(w)] = top
        followable.update(r["filer_id"] for r in top)

    with open("output/performance_leaderboard.json") as f:
        performance = json.load(f)[:TOP_N]
    followable.update(r["filer_id"] for r in performance)

    with open("output/committee_conflicts.json") as f:
        committee = json.load(f)[:TOP_N]
    followable.update(r["filer_id"] for r in committee)

    recent_trades = {}
    for filer_id in followable:
        filer_trades = [t for t in trades if t.get("filer_id") == filer_id]
        filer_trades.sort(key=lambda t: t.get("transaction_date") or "", reverse=True)
        recent = []
        for t in filer_trades[:RECENT_TRADES_N]:
            recent.append(
                {
                    "date": t.get("transaction_date"),
                    "ticker": resolve_ticker(t) or None,
                    "asset_name": t.get("asset_name"),
                    "type": t.get("transaction_type"),
                    "amount_range": t.get("amount_range_label"),
                    "filing_date": t.get("filing_date"),
                    "doc_url": t.get("doc_url"),
                }
            )
        recent_trades[filer_id] = recent

    members = {}
    for filer_id in followable:
        f = filers[filer_id]
        members[filer_id] = {
            "name": f.get("full_name"),
            "chamber": f.get("chamber"),
            "party": f.get("party"),
            "state": f.get("state"),
            "office": f.get("office"),
        }

    bundle = {
        "generated_at": __import__("datetime").datetime.utcnow().isoformat() + "Z",
        "windows": WINDOWS,
        "matches_by_window": matches_by_window,
        "permutation_by_window": permutation_by_window,
        "performance_leaderboard": performance,
        "committee_conflicts": committee,
        "members": members,
        "recent_trades": recent_trades,
    }

    out_path = "../js/congress-data.js"
    with open(out_path, "w") as f:
        f.write("// Generated by analysis/export_for_app.py -- do not hand-edit.\n")
        f.write("const CONGRESS_DATA = ")
        json.dump(bundle, f, indent=2)
        f.write(";\n")

    import os
    size_kb = os.path.getsize(out_path) / 1024
    print(f"Wrote {out_path} ({size_kb:.0f} KB), {len(followable)} followable members, "
          f"{len(members)} member records.")


if __name__ == "__main__":
    main()
